# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: point_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13point_service.proto\x12\x0cpointservice\"/\n\x0cPointRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06points\x18\x02 \x01(\x05\"6\n\rPointResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_points\x18\x02 \x01(\x05\"-\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_points\x18\x02 \x01(\x05\"-\n\x08UserList\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.pointservice.User\"\x07\n\x05\x45mpty2\xd8\x01\n\x0cPointService\x12\x44\n\tAddPoints\x12\x1a.pointservice.PointRequest\x1a\x1b.pointservice.PointResponse\x12I\n\x0eSubtractPoints\x12\x1a.pointservice.PointRequest\x1a\x1b.pointservice.PointResponse\x12\x37\n\x08GetUsers\x12\x13.pointservice.Empty\x1a\x16.pointservice.UserListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'point_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINTREQUEST']._serialized_start=37
  _globals['_POINTREQUEST']._serialized_end=84
  _globals['_POINTRESPONSE']._serialized_start=86
  _globals['_POINTRESPONSE']._serialized_end=140
  _globals['_USER']._serialized_start=142
  _globals['_USER']._serialized_end=187
  _globals['_USERLIST']._serialized_start=189
  _globals['_USERLIST']._serialized_end=234
  _globals['_EMPTY']._serialized_start=236
  _globals['_EMPTY']._serialized_end=243
  _globals['_POINTSERVICE']._serialized_start=246
  _globals['_POINTSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
