# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pointstudent.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pointstudent.proto\")\n\x0cPointRequest\x12\n\n\x02id\x18\x01 \x01(\x01\x12\r\n\x05point\x18\x02 \x01(\x01\";\n\rPointResponse\x12\n\n\x02id\x18\x01 \x01(\x01\x12\r\n\x05point\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\"%\n\x08UserList\x12\x19\n\x07student\x18\x01 \x03(\x0b\x32\x08.Student\"5\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x01\x12\r\n\x05point\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\x8a\x01\n\x0cStudetnPoint\x12*\n\tAddPoints\x12\r.PointRequest\x1a\x0e.PointResponse\x12/\n\x0eSubtractPoints\x12\r.PointRequest\x1a\x0e.PointResponse\x12\x1d\n\x08GetUsers\x12\x06.Empty\x1a\t.UserListB/\n\x1d\x63om.example.send.grpc_studentB\x0cStudentPointP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pointstudent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.example.send.grpc_studentB\014StudentPointP\001'
  _globals['_POINTREQUEST']._serialized_start=22
  _globals['_POINTREQUEST']._serialized_end=63
  _globals['_POINTRESPONSE']._serialized_start=65
  _globals['_POINTRESPONSE']._serialized_end=124
  _globals['_USERLIST']._serialized_start=126
  _globals['_USERLIST']._serialized_end=163
  _globals['_STUDENT']._serialized_start=165
  _globals['_STUDENT']._serialized_end=218
  _globals['_EMPTY']._serialized_start=220
  _globals['_EMPTY']._serialized_end=227
  _globals['_STUDETNPOINT']._serialized_start=230
  _globals['_STUDETNPOINT']._serialized_end=368
# @@protoc_insertion_point(module_scope)
